[files]
ignore-dot = true
ignore-files = true
extend-exclude = ["themes/", "data/", "static-surprises/", "resources/"]

[default]
binary = false
# Words to ignore
extend-ignore-re = ["crypted", "daed", "fo", "ba", "edn", "noice"]
