{
  imports = [
    ./agenix
    ./core-packages.nix
    ./development.nix
    ./games.nix
    ./greetd.nix
    ./home-manager.nix
    ./kdeconnect.nix
    ./locale.nix
    ./networking.nix
    ./niri.nix
    ./nix-ld.nix
    ./nix.nix
    ./nixos-options.nix
    ./nixpkgs.nix
    ./openssh.nix
    ./pipewire.nix
    ./podman.nix
    ./printing.nix
    ./quietboot.nix
    ./security.nix
    ./smb.nix
    ./systemd-initrd.nix
    ./upower.nix
    ./wireless.nix
    ./zsh.nix
  ];
}
